export const ImagesAssets = {
  builder: require('./builder.png'),
  electrician: require('./electrician.png'),
  gardener: require('./gardener.png'),
  loader: require('./loader.png'),
  worker: require('./worker.png'),
  information: require('./information.png'),
  important: require('./important.png'),
  house: require('./house.png'),
  newspaper: require('./newspaper.png'),
  alert: require('./alert.png'),
  add: require('./add.png'),
  service: require('./service.png'),
  refresh: require('./refresh.png'),
  defaultImage: require('./defaultImage.png'),
  backGroundImage: require('../../appJpg/backGround.jpg'),
  star: require('../../appSvg/star.svg'),
  document: require('./document.png'),
  government: require('./government.png'),
  mail: require('./mail.png'),
};
